from enum import Enum, IntEnum

MAX_BID = 50000

class Status(str, Enum):
    RECIEVED = 'RECIEVED'
    PROCESSING = 'PROCESSING'
    BID = 'BID'
    USER_ACCEPTED = 'USER_ACCEPTED'
    USER_DECLINED = 'USER_DECLINED'
    EXPIRED = 'EXPIRED'
    ERROR = 'ERROR'
    REJECTED = 'REJECTED'

class EmploymentStatus(str, Enum):
    UNEMPLOYED = 'UNEMPLOYED'
    SELF_EMPLOYED = 'SELF_EMPLOYED'
    EMPLOYED = 'EMPLOYED'

class Purpose(str, Enum):
    EXPANSION = 'EXPANSION'
    RESTRUCTURING = 'RESTRUCTURING'
    AVOID_BANKRUPTCY = 'AVOID_BANKRUPTCY'
